version: '3'

services:
  ml-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
